### ISSUE TITLE
Unable to deeply customize grub conf

### ISSUE THREAD

**Issue by ThibsG** [drakkar-lig/debootstick#12]
In order to build very customized bootable image, i want to change some of the flags in grub configuration.
We already can customize GRUB_CMDLINE_LINUX with --config-kernel-bootargs, but we can't do the same for other Grub flags (GRUB_TERMINAL, GRUB_DISABLE_RECOVERY etc.).

I identified 2 ways to do this:
- adding a new option replacing any Grub flag with another one:
--config-kernel-boot**flags** "-GRUB_TIMEOUT=5 +GRUB_TIMEOUT=0"
- more generic way: allow user to execute custom scripts after installation is performed (grub included) but before the iso file is built

Bonus: i think hard to deal with --config-kernel-bootargs, because you need to browse the source code (or look at generated file /etc/default/grub) to know what default values are used. 
For example, if you want to put 'rootdelay=0' in grub conf, you have to specify '-rootdelay=3 +rootdelay=0' (you have to know the '3' default value).
Didn't find a better way to do this, but note that my second option can help here: the user can replace the entire line.

What do you think ?

**Comment by eduble** [comment]
Hi, in my opinion, debootstick main role is not to customize the OS, because customization options are countless and a tool with too many options would be hard to use.
Thus, in your case, I would favor an installation of grub-pc package and its customzation before your call debootstick, if ever that is possible. How do you generate the OS tree, before you call debootstick?

When you run debootstick, you may see a line "installing missing packages: <list-of-packages>". In this case, I usually copy-paste this <list-of-packages> to OS tree generation step (e.g. by adding **--include <list-of-packages>** to deboot**strap**). Then, debootstick will bypass this step, and run faster. Plus, you can customize as you wish between those 2 steps.

About the '-rootdelay=3 +rootdelay=0' thing, that's annoying. I think we should enhance this option in a way or another...
I added rootdelay=3 because on a real machine, when booting an LVM volume on an USB device, the kernel has to wait for the USB device to be detected, so this is needed, most of the time. Did you try on a real machine?

**Comment by ThibsG** [comment]
Hey, your workaround worked very well.
I guessed at first that the use of grub tools (through debootstick) will overwrite the configuration.
But it's not so i customized the flags in Dockerfile/debootstrap env before i call debootstick, and it works perfectly.

About the `-rootdelay=3 +rootdelay=0` thing, what about a new option like `--config-kernel-bootargs-override` ? Thus, the user can properly do not include the default ones, and if he does, he just has to know what he is using (may be helping with a bunch of doc).

By the way, nice work for debootstick, and i look forward the arch support !

**Comment by eduble** [comment]
That's the strength of debootstick, to focus on bootable image generation only, and let other tools do the rest. It gives you more flexibility.

> About the `-rootdelay=3 +rootdelay=0` thing, what about a new option like `--config-kernel-bootargs-override` ? Thus, the user can properly do not include the default ones, and if he does, he just has to know what he is using (maybe helping him with a bunch of doc).

That's an option, yes.
Or, we may make the existing option `--config-kernel-bootargs` smarter. We could process `<name>=<value>` bootargs differently. I mean, if we specify `rootdelay=0`, that's obvious that we want to override the previous `<value>`. And if we specify `-rootdelay`, we obviously want to suppress any `rootdelay` or `rootdelay=<value>` option.
What do you think?
In any case the default bootargs should be specified in the manpage.

> By the way, nice work for debootstick, and i look forward the arch support !

Thanks!
Right now I am working on raspbian support. In a few days, debootstick should be able to generate Raspberry Pi SD card images.
I think this work could be a first step if we want to extend the tool more (beyond debian-based).

**Comment by ThibsG** [comment]
Yes for `--config-kernel-bootargs`, it would be a better and more intuitive solution, definitely!

**Comment by eduble** [comment]
OK. I will see when I have a little time to improve this.

**Comment by eduble** [comment]
Hi again, commit a07de4f39e1c8bec6cefff35a9a8156fcc037581 includes the changes foreseen.

To summarize, a given bootarg comes from one of the following places:
1. It may be specified in the existing bootloader configuration, in the provided _chroot_.
2. It may be added by debootstick because it is obviously needed (eg. `root=<something>`) or recommended (eg. `rootdelay=<delay>`, needed for a successful boot on most physical machines).
3. It may be specified on the command line using option `--config-kernel-bootargs`.

We now ensure the following order of precedence: 3>2>1.

And `<name>=<value>` options are now treated as expected. For example, regarding the fact that debootstick defines `rootdelay=3` by default: if you write `--config-kernel-bootargs -rootdelay` on the command line, this option will be removed; and if you write `--config-kernel-bootargs rootdelay=1` on the command line, this option will override the default.

Closing the issue, thanks for reporting. :)
