### ISSUE TITLE
Wishlist: Allow generate cdrom image to create live-cds

### ISSUE THREAD

**Issue by i5513** [drakkar-lig/debootstick#13]
Hello,

After running debootstick on a debian sid chroot, and generating the iso. It will run fine on my kvm

But If I load it from CDROM on esxi 4.1 it won't boot

Do you have any hint about how to make it run on vmware ?

Thank you !
PD: Maybe a FAQ entry ?

**Comment by i5513** [comment]
Sorry I forgot about  ISO 9660 / UDF format. Now I totally understand why it is not working.

I wanted to use your tool for making a live cd to recover a system

On vmware 4.1 to recover a system you can attach a CDROM to the vm and then work with its disks

Sorry for the confusion, so this issue should be labeled like "Please, add support to create CDROM image"

Thanks !

**Comment by eduble** [comment]
> On vmware 4.1 to recover a system you can attach a CDROM to the vm and then work with its disks

And you cannot attach the debootstick image as the primary disk and boot on it?

> Sorry for the confusion, so this issue should be labeled like "Please, add support to create CDROM image"

ISO booting is quite different from what debootstick does, so that would require much work.
Plus, as I said, this is a motivated design choice, to favor disk images.
Plus, optical disks is almost an obsolete technology nowadays! :)
Thus sorry but you should not expect too much that debootstick would evolve this way...
