### ISSUE TITLE
Add support for Ubuntu 18.04 Bionic Beaver

### ISSUE THREAD

**Issue by nathan-sain** [drakkar-lig/debootstick#14]

**Comment by eduble** [comment]
Hello,
Thanks for your interest in debootstick.
I will check it out. I know `debootstick --help-os-support` does not list Ubuntu 18.04 yet, but It might just work actually. Did you try it yourself? I know there is an issue with debootstick on 32bits ubuntu, I will fix it shortly, but on a 64bits architecture it might just work.
Thanks
Etienne

**Comment by eduble** [comment]
Hi, I pushed the fix for 32bits chroot environments. And another fix for UEFI boot which was broken. Ubuntu 18.04 was already well handled for 64bits BIOS systems.
The top of master at commit:be2fe60729e5596716709a76dadfce58ebe33ef0 includes those fixes, so you can clone and you should get no issues.
You can reopen another issue if I am wrong.
