### ISSUE TITLE
add option to specify the target VG name (for the migration)

### ISSUE THREAD

**Issue by dmuhamedagic** [drakkar-lig/debootstick#23]
Would you accept a patch for this?

**Comment by eduble** [comment]
Sure, thanks.

**Comment by dmuhamedagic** [comment]
It turned out that this was a pandora box and I'm still not sure what to do about it.
Giving the VG a name which is not unique (no uuid) makes it impossible to boot from the USB stick if such a VG has already been installed on the local disk (two VGs with the same name, everything goes ballistic).
So, I decided to try with the vgrename after pvmove, but then grub fails because it wants to the original VG. I didn't find any way to make grub produce a config with the rootfs which is not the current rootfs; and the grub documentation has most often been unhelpful including in this case.
Would you have by any chance have some suggestions?

**Comment by dmuhamedagic** [comment]
What grub says:
grub-probe: error: failed to get canonical path of `/dev/mapper/DBSTCK--9ddde090-ROOT'.
Because, after vgrename, DBSTCK-blah is gone. BTW, I'm not sure where does grub-probe come from, I guess from update-grub, but no idea what invokes that.

**Comment by dmuhamedagic** [comment]
Maybe to use root=PARTUUID=...... instead of the root=/dev/...
I wonder how to ask grub-mkstandalone to use the PARTUUID instead of the rootfs path.

**Comment by eduble** [comment]
> What grub says:
grub-probe: error: failed to get canonical path of `/dev/mapper/DBSTCK--9ddde090-ROOT'.
Because, after vgrename, DBSTCK-blah is gone. BTW, I'm not sure where does grub-probe come from, I guess from update-grub, but no idea what invokes that.

This is `$BOOTLOADER_INSTALL ${TARGET}` command, a few lines below in the migration script.
`BOOTLOADER_INSTALL` is defined in `/dbstck.conf`. And it should be `grub-install` (if I remember well), which calls `grub-probe` internally.

The migration script has to:
* copy non lvm partitions (EFI boot partition and bios boot partition)
* use `pvmove` to move the LVM volume holding the root filesystem
* and, in order to make the new disk bootable on BIOS-based systems, update the master-boot-record. This in done with this `BOOTLOADER_INSTALL` command.

The master-boot-record has to know where grub is installed: this is at `[root-lvm-volume]/boot`. That is why `grub-install` probes the current setup. The fact you renamed the LVM vg probably prevents it to make the link between `/`, still on a volume named `/dev/mapper/DBSTCK--9ddde090-ROOT', and the renamed LVM vg.

I wonder if we cannot add options to `grub-install` to specify things ourselves and prevent automatic probing.

**Comment by eduble** [comment]
> Maybe to use root=PARTUUID=...... instead of the root=/dev/...
I wonder how to ask grub-mkstandalone to use the PARTUUID instead of the rootfs path.

`grub-mkstandalone` is used only for UEFI boot.
So, if you are booting using BIOS, this is not relevant.
But of course, in should still work in both cases, of course.

When booting with UEFI, here is how it works:
* the machine firmware reads the UEFI boot partition content, and loads the standalone grub binary generated during image creation.
* inside this standalone grub binary, a grub script was embedded. It is run.
* the script looks for the LVM volume holding the root partition.
* here is the interesting trick: it reads and execute the script at `[root-lvm-volume]/boot/grub/grub.cfg`. This script will handle the rest of the bootup procedure.

This secondary script is actually the one that is used for BIOS booting. Thus, this technique allows to use the same script for BIOS and UEFI boot. This is important. Because a debian OS will not let you install both the UEFI grub package and the BIOS grub package. So `debootstick` only installs the BIOS grub package. But, with this technique, the image can also be booted on UEFI-only machines. And, if the grub script needs to be updated (package update, user adding a kernel bootarg, etc.), then it can be done the usual way (grub package update, or calling `update-grub`, etc.), and the UEFI boot will take the change into account too.

**Comment by dmuhamedagic** [comment]
Tried with grub-install -s --force and also edited grub.cfg with the new root=, but it still complains about not finding the canonical path.

**Comment by dmuhamedagic** [comment]
Just looked at the grub code, there's no way to ask grub-install not to canonicalize the root path. I wonder if there's a way to make it not look at the current root path, but to specify it in some way.

**Comment by dmuhamedagic** [comment]
Actually, the problem is that the mount table is not updated, it should be showing the new path (with the new VG name).

**Comment by dmuhamedagic** [comment]
OK, after reading more of the grub2 source, I managed somehow. It doesn't look entirely kosher, but it should do:
```
mount /dev/<newvg>/ROOT /dir
grub-install -s --boot-directory=/dir
```

**Comment by dmuhamedagic** [comment]
Have this implemented, will make a PR next week.

**Comment by eduble** [comment]
Since commit 084554c993e943d165de32a1263fa34c8715f6b3 you can now specify option `lvm_vg_name` in your custom disk layout file (using option `--disk-layout`). Check out the man page for more info.
