### ISSUE TITLE
Chroot env must be debian/ubuntu based

### ISSUE THREAD

**Issue by Clement-TS** [drakkar-lig/debootstick#7]
Hi,
I'm now playing around with a light alpine linux image, I would like to boot it on an usbkey / pxe for instance. I give a try to debootstick:

```
$ debootstick ./rootfs/ ./alpine.img
debootstick should be run as root. Trying sudo...
E: No apt-get found in ./rootfs/.
E: debootstick cannot handle this kind of chroot environment.
```

but it seems that it doesn't support filesystems without apt. What is it done under the hood? This could eventually be fixed with some proper docker calls.

Thank you

**Comment by eduble** [comment]
Hi, thanks for trying. :)

Yes, debootstick only works with debian-based environments, at least for now.

Here is what's done under the hood (a little simplified):
- it creates a blank image file first
- it defines partitions and setup filesystems on it
- it copies the provided rootfs inside one of these partitions
- it installs packages needed for a viable bootable system that were missing in the provided rootfs (linux kernel & bootloader packages, plus a few more needed for the first boot procedure)
- it sets up bootloaders (BIOS and UEFI)

And you get an image ready to be burn on a USB key.

Note that debootstick is **not** based on docker. (You may _use it with docker_, i.e. prepare your rootfs as a docker container, then export it when it's done and give it to debootstick. See [this wiki page](https://github.com/drakkar-lig/debootstick/wiki/Docker).)

If we want debootstick to run other kinds of operating systems, then we will have to manage several kinds of "recipes", in order to adapt at least the package installation step.

The alpine linux distribution has its own package manager, apk, so we would have to run this instead, and look for the name of the packages we need. Unless something we need is missing in alpine repos, that would not be a big change. I might add this kind of things in a future version.

**Comment by eduble** [comment]
Or, of course, if you are interested, you might fork the repo and propose such a change as a pull request. I would be happy to welcome a new contribution.

**Comment by Clement-TS** [comment]
Hi !
thank you for your feedback and info :)

> for my proper/immediate work case, I just found out that the alpine-linux community already achieved a great piece of art: http://git.alpinelinux.org/cgit/alpine-iso/tree/Makefile

However I'm quiet sure it's possible to create a generic tool, capable of handling as many *"recipes"* as we could imagine, assuming we give a *rootfs*, an *initramfs*, a *kernel* and optional *boot entries*:

```
                     .----------.
   rootfs    ---->   |          |
   kernel    ---->   |          |
initramfs    ---->   |   Tool   |  -----> iso file
boot options ---->   |          |
                     |          |
                     `----------'
```

As you mentioned, it's really easy to create a *rootfs* based on a docker container ([docker export](https://docs.docker.com/engine/reference/commandline/export/)). Then in a docker context we can easily play with the packaging system, add *kernel(s)*, generate *initramfs*, reactivate the *init system* (which is [disabled for docker usage](https://github.com/tianon/docker-brew-ubuntu-core/blob/b6f1fe19228e5b6b7aed98dcba02f18088282f90/xenial/Dockerfile))... 

I think the only extra thing to do would be to update the `/etc/fstab` *rootfs* file to match the partitioning setup created by the tool (ie. *debootstick*). Do you agree with that? Did I missed something?

And, what do you mean by `plus a few more needed for the first boot procedure`?$

Thanks!

**Comment by eduble** [comment]
One of the goals of debootstick is to generate OS bootable images that are **viable on the long term**.

Usually, official images of most linux distributions are **not**. They are designed to _test the system_ or to _install it on the machine's disk_. And there are tricks to put as much software as possible on it (using a readonly squashfs layer usually). Because of this complexity, for example if you try to boot an official Ubuntu distro on USB, you will notice that you cannot upgrade the kernel or bootloader. Those files are not part of the root filesystem, and thus they cannot be updated by usual software. Of course this is a major security issue if ever you want to use this on the long term.

On the other hand, when you generate an image with debootstick, the system there has the same structure as an OS installed on a disk. The bootloader is grub, not isolinux, there is no read-only layer, etc. Thus you can _really_ upgrade your OS, as you would do on a regular OS. Just because _it is_ a regular OS. The image itself is not a CD-bootable iso, it is basically like a dump of a hard-disk.

I think I understand what you mean by the "generic tool" you imagine. If the whole bootup procedure (kernel, initramfs, etc) is defined statically at build time then of course such a generic tool could be written quite easily. But then you do not fulfill the same goal as debootstick.

About your last question:
debootstick does not embed a compressed filesystem layer, but still, it tries to generate an image as small as possible, by trying to compute the minimal size needed for the rootfs partition.
Let's say it estimates a minimal size of 100Mb for your rootfs partition. Then the image will be around 102Mb maybe (there are 2 other partitions for UEFI and BIOS boot codes). You dump this image on a USB key 2Go large. Then at first boot, if you type `df`, you would see the partition space usage is something like "99%".
That's why some code is executed at first boot: it allows to extend the partition on the free space of the USB key.

Note that there is an option `--system-type installer` which alters this behaviour on first boot. In this case, the system will automatically migrate itself to the hard-disk of the machine (after you confirm it, of course). Then you can unplug the USB key and enjoy your debootstick-generated OS.

**Comment by eduble** [comment]
Hi, I have checked out a little.
I think it would not be very interesting to get debootstick working with alpine, for now, because:
- debootstick requires grub for now (this allows to get both BIOS and UEFI booting capabilities), alpine's default is extlinux.
- in order to avoid disk space issues on the long term (who knows if we should make /boot 100M bigger, or 100M smaller and get a bigger root filesystem?), there is no separate /boot partition. Thus, debootstick creates only 1 partition for the whole root filesystem. This partition is actually a LVM volume (this allows advanced features such as live migration from bootable media to main disk). Grub works with this kind of setup, extlinux does not.

Installing things such as grub and lvm in alpine would still be possible, but I think you would not be very satisfied with such a generated image: Alpine is designed to be small, and I think this image would not be so small.

In the future, I may provide options to generate alternate image structures (no lvm, for example). This would disallow some of the features, but it would allow to generate smaller images. After this is done, it would make much more sense to support Alpine.
So I close the pull request for now, and will re-open it if debootstick evolves this way.
